#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_FRISK                               102
#define IDI_FRISK                               107
#define IDI_SMALL                               108
#define IDD_SETTINGS                            129
#define IDC_BROWSE                              1001
#define IDC_STOP                                1002
#define IDC_MATCH                               1003
#define IDC_PATH                                1004
#define IDC_FILESPEC                            1005
#define IDC_SEARCH                              1006
#define IDC_DOREPLACE                           1007
#define IDC_OUTPUT                              1008
#define IDC_REPLACE                             1009
#define IDC_FILESIZE                            1010
#define IDC_STATE                               1011
#define IDC_FILESPEC_REGEX                      1012
#define IDC_FILESPEC_CASE                       1013
#define IDC_MATCH_REGEXES                       1014
#define IDC_MATCH_CASE                          1015
#define IDC_RECURSIVE                           1016
#define IDC_SETTINGS                            1017
#define IDC_COLOR_TEXT                          1018
#define IDC_COLOR_BG                            1019
#define IDC_LOAD                                1019
#define IDC_CMD                                 1020
#define IDC_SAVE                                1021
#define IDC_COLOR_HIGHLIGHT                     1022
#define IDC_SAVEDSEARCHES                       1022
#define IDC_CMD_ASSOC                           1028
#define IDC_CMD_NOTEPAD                         1029
#define IDC_BACKUP_EXT                          1030
#define IDC_TRIM_FILENAMES                      1032
#define IDC_BACKUP                              1033
#define IDC_DELETE                              1035
#define IDC_COLOR_CONTEXT                       40000
#define IDC_FONT_DESC                           40001
#define IDC_FONT                                40002
